CREATE TABLE "survey_responses" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text,
	"email" text,
	"phone" text,
	"law_firm" text,
	"position" text,
	"years_of_practice" text,
	"firm_size" text,
	"practice_areas" text[],
	"current_tools" text[],
	"document_storage" text,
	"workflow_description" text,
	"challenge_documents" integer,
	"challenge_deadlines" integer,
	"challenge_client_communication" integer,
	"challenge_case_tracking" integer,
	"challenge_compliance_tracking" integer,
	"challenge_billing" integer,
	"biggest_challenge" text,
	"feature_matter_management" integer,
	"feature_document_management" integer,
	"feature_reminders" integer,
	"feature_client_portal" integer,
	"feature_task_management" integer,
	"feature_billing" integer,
	"feature_compliance_tracking" integer,
	"feature_ai_search" integer,
	"litigation_percentage" integer,
	"corporate_percentage" integer,
	"compliance_percentage" integer,
	"tax_percentage" integer,
	"company_secretarial_percentage" integer,
	"interested_in_pilot" text,
	"willing_to_pay" text,
	"contact_for_prototype" text,
	"magic_wand_problem" text,
	"additional_comments" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
